development:
  adapter: postgresql
  database: instun_new
  encoding: sql_ascii
  username: postgres
  pool: 5
  password: pas12345
  host: localhost

test:
  adapter: postgresql
  database: instun_t
  username: pgsql
  password:
  pool: 5
  host: localhost

production:
  adapter: postgresql
  database: instun
  username: pgsql
  password:
  host: localhost
